---
# absent tasks file for caddy_docker

- name: absent | Remove Caddy directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ caddy_docker_config_directory }}"
    - "{{ caddy_docker_data_directory }}"
    - "{{ caddy_docker_caddyfile_directory }}"

- name: absent | Caddy with plugins
  when: caddy_docker_plugins
  block:
    - name: absent | Remove Caddy builder directory
      ansible.builtin.file:
        path: "{{ caddy_docker_builder_directory.path }}"
        state: absent

    - name: absent | Remove Caddy container image
      community.docker.docker_image:
        name: "caddy-custom:plugins"
        state: absent

- name: absent | Remove Caddy Docker network(s)
  when: caddy_docker_network_mode != "host"
  community.docker.docker_network:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ caddy_docker_networks }}"

- name: absent | Remove Caddy Docker container
  community.docker.docker_container:
    name: caddy
    state: absent
