---
# tasks file for caddy_docker

- name: Present | Caddy Docker
  ansible.builtin.import_tasks: present.yml
  when: caddy_docker_state == "present"

- name: Absent | Caddy Docker
  ansible.builtin.import_tasks: absent.yml
  when: caddy_docker_state == "absent"
