---
- name: Converge
  hosts: all
  vars:
    pip_install_packages:
      - name: docker
  pre_tasks:
    - name: Install Ansible roles
      delegate_to: localhost
      block:
        - name: Install geerlingguy.pip role
          community.general.ansible_galaxy_install:
            type: role
            name: geerlingguy.pip

        - name: Install geerlingguy.docker role
          community.general.ansible_galaxy_install:
            type: role
            name: geerlingguy.docker

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    # Credit: https://github.com/geerlingguy/ansible-role-docker/blob/master/molecule/default/converge.yml#L11
    - name: Wait for systemd to complete initialisation  # noqa 303
      ansible.builtin.command:
        cmd: systemctl is-system-running
      register: systemctl_status
      until: >
        "running" in systemctl_status.stdout or
        "degraded" in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == "systemd"
      changed_when: false
      failed_when: systemctl_status.rc > 1
  tasks:
    - name: Include geerlingguy.pip
      ansible.builtin.include_role:
        name: geerlingguy.pip

    - name: Include geerlingguy.docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

    - name: Include dbrennand.caddy_docker
      ansible.builtin.include_role:
        name: dbrennand.caddy_docker
