---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-debian11-ansible:latest
    privileged: true
    pre_build_image: true
    override_command: false
    tmpfs:
      - /tmp
      - /run
      - /run/lock
provisioner:
  name: ansible
verifier:
  name: ansible
