FROM {{ caddy_docker_builder_image }}:{{ caddy_docker_builder_image_tag }} AS builder

RUN xcaddy build \
    {{% for plugin in caddy_docker_plugins %}}
    --with {{ plugin }} {{ \ if not loop.last }}
    {{% endfor %}}

FROM {{ caddy_docker_image }}:{{ caddy_docker_image_tag }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
