FROM {{ caddy_builder_image }}:{{ caddy_builder_image_tag }} AS builder

RUN xcaddy build \
    {{% for plugin in caddy_plugins %}}
    --with {{ plugin }} {{ \ if not loop.last }}
    {{% endfor %}}

FROM {{ caddy_image }}:{{ caddy_image_tag }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
