---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify Caddy is responding on localhost
      ansible.builtin.uri:
        url: http://localhost
        return_content: true
        validate_certs: false
      register: caddy_resp
      failed_when: "'Hello, world!' not in caddy_resp.content"

    - name: Verify Caddy Docker networks do not exist
      community.docker.docker_network_info:
        name: "{{ item.name }}"
      with_items: "{{ caddy_docker_networks }}"
      register: network_result
      failed_when: network_result.exists
