name: Ansible Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

defaults:
  run:
    working-directory: "dbrennand.caddy_docker"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "dbrennand.caddy_docker"

      - id: repository_name
        run: echo "::set-output name=repository_name::$(echo ${{ github.repository }} | cut -d / -f 2)"

      - id: role_name
        run: echo "::set-output name=role_name::$(yq -r '.galaxy_info.role_name' meta/main.yml)"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip3 install ansible-core

      - run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} --role-name ${{ steps.role_name.outputs.role_name }} ${{ github.repository_owner }} ${{ steps.repository_name.outputs.repository_name }}
